# AniData Lab : Rapport d'Audit Du Dataset

## Objectifs de cet audit

1. Explorer les 3 fichiers CSV sources (anime, ratings, synopsis)
2. Identifier les problèmes de qualité : valeurs manquantes, doublons, types incohérents, encodages
3. Produire des statistiques descriptives et un profiling automatisé
4. Documenter les anomalies et recommandations de nettoyage

# 1 Mise En Place et Chargement Des Données

In [6]:
import numpy as np
import pandas as pd

In [ ]:
# Variablisation du repertoire source pour meilleur robustesse 
REP_SOURCE = "../data"

In [22]:
animelist = pd.read_csv(f"{REP_SOURCE}/animelist.csv")
anime = pd.read_csv(f"{REP_SOURCE}/anime.csv")
rating_complete = pd.read_csv(f"{REP_SOURCE}/rating_complete.csv")
anime_with_synopsis = pd.read_csv(f"{REP_SOURCE}/anime_with_synopsis.csv")

# 2 EDA et Audit de animelist

In [17]:
animelist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109224747 entries, 0 to 109224746
Data columns (total 5 columns):
 #   Column            Dtype
---  ------            -----
 0   user_id           int64
 1   anime_id          int64
 2   rating            int64
 3   watching_status   int64
 4   watched_episodes  int64
dtypes: int64(5)
memory usage: 4.1 GB

In [19]:
animelist.isnull().sum()

user_id             0
anime_id            0
rating              0
watching_status     0
watched_episodes    0
dtype: int64

In [14]:
animelist.describe()

,user_id,anime_id,rating,watching_status,watched_episodes
count,1.092247e+08,1.092247e+08,1.092247e+08,1.092247e+08,1.092247e+08
mean,1.768098e+05,1.649590e+04,4.245717e+00,3.087289e+00,1.210818e+01
std,1.018487e+05,1.379737e+04,3.912888e+00,1.774407e+00,1.463155e+02
min,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,8.849100e+04,3.194000e+03,0.000000e+00,2.000000e+00,0.000000e+00
50%,1.771420e+05,1.244500e+04,5.000000e+00,2.000000e+00,3.000000e+00
75%,2.651870e+05,3.083100e+04,8.000000e+00,6.000000e+00,1.200000e+01
max,3.534040e+05,4.849200e+04,1.000000e+01,5.500000e+01,6.553500e+04

In [12]:
animelist.head()

   user_id  anime_id  rating  watching_status  watched_episodes
0        0        67       9                1                 1
1        0      6702       7                1                 4
2        0       242      10                1                 4
3        0      4898       0                1                 1
4        0        21      10                1                 0

In [21]:
nb_null_animelist = animelist.duplicated().sum()
print(nb_null_animelist)

1

In [23]:
animelist = animelist.drop_duplicates()
nb_null_animelist = animelist.duplicated().sum()
print(nb_null_animelist)

0

In [24]:
animelist[["user_id", "anime_id"]].duplicated().sum()

np.int64(0)

In [28]:
animelist["rating"].value_counts()

rating
0     46827034
8     15422150
7     14244633
9     10235934
6      7543377
10     7144392
5      4029645
4      1845854
3       905700
2       545339
1       480688
Name: count, dtype: int64

In [35]:
animelist["watching_status"].unique()

array([ 1,  2,  3,  4,  6,  0,  5, 33, 55])

In [49]:
animelist["watching_status"].value_counts()

watching_status
2     68089751
6     27938692
1      5228658
4      4266591
3      3700514
0          531
5            6
33           2
55           1
Name: count, dtype: int64

In [50]:
animelist["watching_status"] = animelist["watching_status"].replace({33: 3, 55: 5})

In [51]:
animelist["watching_status"].value_counts()

watching_status
2    68089751
6    27938692
1     5228658
4     4266591
3     3700516
0         531
5           7
Name: count, dtype: int64

In [ ]:
animelist["watched_episodes"].unique()

np.int64(65535)

In [47]:
animelist["watched_episodes"].unique().max()

np.int64(65535)

In [48]:
animelist["watched_episodes"].unique().min()

np.int64(0)

In [45]:
animelist["watched_episodes"].describe()

count    1.092247e+08
mean     1.210818e+01
std      1.463155e+02
min      0.000000e+00
25%      0.000000e+00
50%      3.000000e+00
75%      1.200000e+01
max      6.553500e+04
Name: watched_episodes, dtype: float64